apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: devops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: 300m
              ephemeral-storage: 100M
              memory: 600M
            requests:
              cpu: 300m
              ephemeral-storage: 100M
              memory: 600M
